# =======================================
# 🚀 Minimal Mistakes Jekyll Configuration
# =======================================

# 🔹 THEME SETTINGS
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"  # Choose from "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# 🔹 SITE SETTINGS
locale: "en-US"
title: "Meilin Pan's Portfolio"
title_separator: "-"
name: "Meilin Pan"
description: "A portfolio showcasing my projects, skills, and experience."
url: "https://meilinp.github.io"  # Base URL of your website
baseurl: ""  # Leave empty if hosted at root (meilinp.github.io)
repository: "MeilinP/meilinp.github.io"

# 🔹 LOGO & APPEARANCE
logo: "/assets/images/logo.png"  # Add your logo to `/assets/images/`
masthead_title: " "  # Use an empty string to hide the site title
breadcrumbs: true
words_per_minute: 200
enable_copy_code_button: true

# 🔹 SEO SETTINGS
google_site_verification: ""  # Add your Google Search Console verification code if applicable

# 🔹 SOCIAL LINKS
social:
  type: "Person"
  name: "Meilin Pan"
  links:
    - "https://github.com/MeilinP"
    - "https://www.linkedin.com/in/YOUR_LINKEDIN_ID"

# 🔹 AUTHOR INFO (for blog posts)
author:
  name: "Meilin Pan"
  avatar: "/assets/images/profile.jpg"  # Add your profile picture
  bio: "Master's in Applied Data Science at University of Southern California"
  location: "Los Angeles, CA"
  email: "your-email@example.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MeilinP"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/YOUR_LINKEDIN_ID"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:your-email@example.com"

# 🔹 FOOTER LINKS
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MeilinP"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/YOUR_LINKEDIN_ID"

# 🔹 NAVIGATION BAR (Header Links)
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "Resume"
    url: "/resume/"
  - title: "Blog"
    url: "/blog/"
  - title: "Contact"
    url: "/contact/"

# 🔹 COMMENTS SETTINGS (Optional)
comments:
  provider: false  # Set to "disqus", "utterances", etc., if you want comments.

# 🔹 SEARCH SETTINGS
search: true
search_provider: "lunr"

# 🔹 GOOGLE ANALYTICS (Optional)
analytics:
  provider: "google"
  google:
    tracking_id: "YOUR_GOOGLE_ANALYTICS_ID"

# 🔹 PAGINATION SETTINGS
paginate: 5  # Number of posts per page
paginate_path: "/page:num/"

# 🔹 JEKYLL PLUGINS (Required for Minimal Mistakes theme)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# 🔹 EXCLUDE FILES FROM THE FINAL WEBSITE
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - test/

# 🔹 MARKDOWN & SYNTAX HIGHLIGHTING
markdown: kramdown
highlighter: rouge

# 🔹 HTML COMPRESSION (Reduces file size)
compress_html:
  clippings: all
  ignore:
    envs: development
